install.packages("tidyverse")
library(tidyverse)
install.packages("readxl")

#Import dataset

#Look at data 
names(X1)

#Clean column titles because complex and long
install.packages("janitor")
library(janitor)

X1 <- X1 %>%
  janitor::clean_names()

names(X1)

#Create object 1-metadata
d.metadata <- X1[, c("reference", 
                     "organisation_size", 
                     "user_type", 
                     "organisation_name", 
                     "transparency_register_number")]

head(d.metadata)

#Create object 2-Closed Questions data
d.structure <- X1[, c(
  "reference",
  "organisation_name",
  "in_your_opinion_how_important_are_the_six_actions_proposed_in_section_4_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_working_with_member_states",                                                                                                                                                                                                                                                                                                           
  "in_your_opinion_how_important_are_the_six_actions_proposed_in_section_4_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_focussing_the_efforts_of_the_research_and_innovation_community",                                                                                                                                                                                                                                                                        
  "in_your_opinion_how_important_are_the_six_actions_proposed_in_section_4_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_skills",                                                                                                                                                                                                                                                                                                                                
  "in_your_opinion_how_important_are_the_six_actions_proposed_in_section_4_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_focus_on_sm_es",                                                                                                                                                                                                                                                                                                                        
  "in_your_opinion_how_important_are_the_six_actions_proposed_in_section_4_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_partnership_with_the_private_sector",                                                                                                                                                                                                                                                                                                   
  "in_your_opinion_how_important_are_the_six_actions_proposed_in_section_4_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_promoting_the_adoption_of_ai_by_the_public_sector",                                                                                                                                                                                                                                                                                     
  "in_your_opinion_how_important_is_it_in_each_of_these_areas_to_align_policies_and_strengthen_coordination_as_described_in_section_4_a_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_strengthen_excellence_in_research",                                                                                                                                                                                                                                              
  "in_your_opinion_how_important_is_it_in_each_of_these_areas_to_align_policies_and_strengthen_coordination_as_described_in_section_4_a_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_establish_world_reference_testing_facilities_for_ai",                                                                                                                                                                                                                            
  "in_your_opinion_how_important_is_it_in_each_of_these_areas_to_align_policies_and_strengthen_coordination_as_described_in_section_4_a_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_promote_the_uptake_of_ai_by_business_and_the_public_sector",                                                                                                                                                                                                                     
  "in_your_opinion_how_important_is_it_in_each_of_these_areas_to_align_policies_and_strengthen_coordination_as_described_in_section_4_a_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_increase_the_financing_for_start_ups_innovating_in_ai",                                                                                                                                                                                                                          
  "in_your_opinion_how_important_is_it_in_each_of_these_areas_to_align_policies_and_strengthen_coordination_as_described_in_section_4_a_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_develop_skills_for_ai_and_adapt_existing_training_programmes",                                                                                                                                                                                                                   
  "in_your_opinion_how_important_is_it_in_each_of_these_areas_to_align_policies_and_strengthen_coordination_as_described_in_section_4_a_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_build_up_the_european_data_space",                                                                                                                                                                                                                                               
  "in_your_opinion_how_important_are_the_three_actions_proposed_in_sections_4_b_4_c_and_4_e_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_support_the_establishment_of_a_lighthouse_research_centre_that_is_world_class_and_able_to_attract_the_best_minds",                                                                                                                                                                                                     
  "in_your_opinion_how_important_are_the_three_actions_proposed_in_sections_4_b_4_c_and_4_e_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_network_of_existing_ai_research_excellence_centres",                                                                                                                                                                                                                                                                   
  "in_your_opinion_how_important_are_the_three_actions_proposed_in_sections_4_b_4_c_and_4_e_of_the_white_paper_on_ai_1_5_1_is_not_important_at_all_5_is_very_important_set_up_a_public_private_partnership_for_industrial_research",                                                                                                                                                                                                                                                          
  "in_your_opinion_how_important_are_each_of_these_tasks_of_the_specialised_digital_innovation_hubs_mentioned_in_section_4_d_of_the_white_paper_in_relation_to_sm_es_1_5_1_is_not_important_at_all_5_is_very_important_help_to_raise_sme_s_awareness_about_potential_benefits_of_ai",                                                                                                                                                                                                        
  "in_your_opinion_how_important_are_each_of_these_tasks_of_the_specialised_digital_innovation_hubs_mentioned_in_section_4_d_of_the_white_paper_in_relation_to_sm_es_1_5_1_is_not_important_at_all_5_is_very_important_provide_access_to_testing_and_reference_facilities",                                                                                                                                                                                                                   
  "in_your_opinion_how_important_are_each_of_these_tasks_of_the_specialised_digital_innovation_hubs_mentioned_in_section_4_d_of_the_white_paper_in_relation_to_sm_es_1_5_1_is_not_important_at_all_5_is_very_important_promote_knowledge_transfer_and_support_the_development_of_ai_expertise_for_sm_es",                                                                                                                                                                                     
  "in_your_opinion_how_important_are_each_of_these_tasks_of_the_specialised_digital_innovation_hubs_mentioned_in_section_4_d_of_the_white_paper_in_relation_to_sm_es_1_5_1_is_not_important_at_all_5_is_very_important_support_partnerships_between_sm_es_larger_enterprises_and_academia_around_ai_projects",                                                                                                                                                                                
  "in_your_opinion_how_important_are_each_of_these_tasks_of_the_specialised_digital_innovation_hubs_mentioned_in_section_4_d_of_the_white_paper_in_relation_to_sm_es_1_5_1_is_not_important_at_all_5_is_very_important_provide_information_about_equity_financing_for_ai_startups",                                                                                                                                                                                                           
  "in_your_opinion_how_important_are_the_following_concerns_about_ai_1_5_1_is_not_important_at_all_5_is_very_important_ai_may_endanger_safety",                                                                                                                                                                                                                                                                                                                                               
  "in_your_opinion_how_important_are_the_following_concerns_about_ai_1_5_1_is_not_important_at_all_5_is_very_important_ai_may_breach_fundamental_rights_such_as_human_dignity_privacy_data_protection_freedom_of_expression_workers_rights_etc",                                                                                                                                                                                                                                              
  "in_your_opinion_how_important_are_the_following_concerns_about_ai_1_5_1_is_not_important_at_all_5_is_very_important_the_use_of_ai_may_lead_to_discriminatory_outcomes",                                                                                                                                                                                                                                                                                                                    
  "in_your_opinion_how_important_are_the_following_concerns_about_ai_1_5_1_is_not_important_at_all_5_is_very_important_ai_may_take_actions_for_which_the_rationale_cannot_be_explained",                                                                                                                                                                                                                                                                                                      
  "in_your_opinion_how_important_are_the_following_concerns_about_ai_1_5_1_is_not_important_at_all_5_is_very_important_ai_may_make_it_more_difficult_for_persons_having_suffered_harm_to_obtain_compensation",                                                                                                                                                                                                                                                                                
  "in_your_opinion_how_important_are_the_following_concerns_about_ai_1_5_1_is_not_important_at_all_5_is_very_important_ai_is_not_always_accurate",                                                                                                                                                                                                                                                                                                                                            
  "in_your_opinion_how_important_are_the_following_mandatory_requirements_of_a_possible_future_regulatory_framework_for_ai_as_section_5_d_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_the_quality_of_training_data_sets",                                                                                                                                                                                                                                            
  "in_your_opinion_how_important_are_the_following_mandatory_requirements_of_a_possible_future_regulatory_framework_for_ai_as_section_5_d_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_the_keeping_of_records_and_data",                                                                                                                                                                                                                                              
  "in_your_opinion_how_important_are_the_following_mandatory_requirements_of_a_possible_future_regulatory_framework_for_ai_as_section_5_d_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_information_on_the_purpose_and_the_nature_of_ai_systems",                                                                                                                                                                                                                      
"in_your_opinion_how_important_are_the_following_mandatory_requirements_of_a_possible_future_regulatory_framework_for_ai_as_section_5_d_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_robustness_and_accuracy_of_ai_systems",                                                                                                                                                                                                                                        
"in_your_opinion_how_important_are_the_following_mandatory_requirements_of_a_possible_future_regulatory_framework_for_ai_as_section_5_d_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_human_oversight",                                                                                                                                                                                                                                                              
"in_your_opinion_how_important_are_the_following_mandatory_requirements_of_a_possible_future_regulatory_framework_for_ai_as_section_5_d_of_the_white_paper_1_5_1_is_not_important_at_all_5_is_very_important_clear_liability_and_safety_rules"   
)]

head(d.structure)

#Create object 3-Open Questions data
d.open <- X1[, c(
  "reference",
  "organisation_name",
  "are_there_other_actions_that_should_be_considered",
  "are_there_other_areas_that_that_should_be_considered",                                                                                                                                                                                                                                                                                                                                                                                                                                     
  "are_there_any_other_tasks_that_you_consider_important_for_specialised_digital_innovations_hubs",                                                                                                                                                                                                                                                                                                                                                                                           
  "do_you_have_any_other_concerns_about_ai_that_are_not_mentioned_above_please_specify",                                                                                                                                                                                                                                                                                                                                                                                                      
  "do_you_think_that_the_concerns_expressed_above_can_be_addressed_by_applicable_eu_legislation_if_not_do_you_think_that_there_should_be_specific_new_rules_for_ai_systems",                                                                                                                                                                                                                                                                                                                  
  "other_please_specify",                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  "if_you_think_that_new_rules_are_necessary_for_ai_system_do_you_agree_that_the_introduction_of_new_compulsory_requirements_should_be_limited_to_high_risk_applications_where_the_possible_harm_caused_by_the_ai_system_is_particularly_high",                                                                                                                                                                                                                                               
  "other_please_specify_47",                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  "do_you_agree_with_the_approach_to_determine_high_risk_ai_applications_proposed_in_section_5_b_of_the_white_paper",                                                                                                                                                                                                                                                                                                                                                                         
  "other_please_specify_49",                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  "if_you_wish_please_indicate_the_ai_application_or_use_that_is_most_concerning_high_risk_from_your_perspective",                                                                                                                                                                                                                                                                                                                                                                            
  "in_addition_to_the_existing_eu_legislation_in_particular_the_data_protection_framework_including_the_general_data_protection_regulation_and_the_law_enforcement_directive_or_where_relevant_the_new_possibly_mandatory_requirements_foreseen_above_see_question_above_do_you_think_that_the_use_of_remote_biometric_identification_systems_e_g_face_recognition_and_other_technologies_which_may_be_used_in_public_spaces_need_to_be_subject_to_further_eu_level_guidelines_or_regulation",
  "please_specify_your_answer",                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  "do_you_believe_that_a_voluntary_labelling_system_section_5_g_of_the_white_paper_would_be_useful_for_ai_systems_that_are_not_considered_high_risk_in_addition_to_existing_legislation",                                                                                                                                                                                                                                                                                                     
  "do_you_have_any_further_suggestion_on_a_voluntary_labelling_system",                                                                                                                                                                                                                                                                                                                                                                                                                       
  "what_is_the_best_way_to_ensure_that_ai_is_trustworthy_secure_and_in_respect_of_european_values_and_rules",                                                                                                                                                                                                                                                                                                                                                                                 
  "please_specify_any_other_enforcement_system",                                                                                                                                                                                                                                                                                                                                                                                                                                              
  "do_you_have_any_further_suggestion_on_the_assessment_of_compliance",                                                                                                                                                                                                                                                                                                                                                                                                                       
  "the_current_product_safety_legislation_already_supports_an_extended_concept_of_safety_protecting_against_all_kind_of_risks_arising_from_the_product_according_to_its_use_however_which_particular_risks_stemming_from_the_use_of_artificial_intelligence_do_you_think_should_be_further_spelled_out_to_provide_more_legal_certainty",                                                                                                                                                      
  "in_your_opinion_are_there_any_further_risks_to_be_expanded_on_to_provide_more_legal_certainty",                                                                                                                                                                                                                                                                                                                                                                                            
  "do_you_think_that_the_safety_legislative_framework_should_consider_new_risk_assessment_procedures_for_products_subject_to_important_changes_during_their_lifetime",                                                                                                                                                                                                                                                                                                                        
  "do_you_have_any_further_considerations_regarding_risk_assessment_procedures",                                                                                                                                                                                                                                                                                                                                                                                                              
  "do_you_think_that_the_current_eu_legislative_framework_for_liability_product_liability_directive_should_be_amended_to_better_cover_the_risks_engendered_by_certain_ai_applications",                                                                                                                                                                                                                                                                                                       
  "do_you_have_any_further_considerations_regarding_the_question_above",                                                                                                                                                                                                                                                                                                                                                                                                                      
  "do_you_think_that_the_current_national_liability_rules_should_be_adapted_for_the_operation_of_ai_to_better_ensure_proper_compensation_for_damage_and_a_fair_allocation_of_liability",                                                                                                                                                                                                                                                                                                      
  "please_specify_the_ai_applications",                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  "do_you_have_any_further_considerations_regarding_the_question_above_2",                                                                                                                                                                                                                                                                                                                                                                                                                    
  "you_can_upload_a_document_here"                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  )]

#Change structure to pivot data - shows reference number against each answer
d.metadata.long <- d.metadata %>%
  pivot_longer(
    cols = -"reference",          
    names_to = "Question",      
    values_to = "Response"   
  )

head(d.metadata.long)
dim(d.metadata.long) 

d.structure.long <- d.structure %>%
  pivot_longer(
    cols = -"reference",          
    names_to = "Question",      
    values_to = "Response"   
  )

head(d.structure.long)
dim(d.structure.long)   

d.open.long <- d.open %>%
  pivot_longer(
    cols = -"reference",          
    names_to = "Question",      
    values_to = "Response"   
  )

head(d.open.long)
dim(d.open.long)   

#Save workspace
setwd("~/Desktop")
save.image(file = "EP-1-31Aug2025.RData")

git init

